DROP TABLE IF EXISTS Users;

DROP TABLE IF EXISTS Products;

DROP TABLE IF EXISTS Cart;

DROP TABLE IF EXISTS CartProducts;

DROP TABLE IF EXISTS Categories;

DROP TABLE IF EXISTS ProductDetails;